name: Sync Repository gitee
on:
  push:
  #schedule:
    # 每天北京时间0点同步
    #- cron:  '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: sync github repository
      uses: x-dr/SRA@v2
      env:
          # 在 Settings->Secrets配置 GITEE_KEY
          SSH_KEY: ${{ secrets.GITEE }}
      with:
          # 注意替换为你的源仓库地址
          github-repo: "git@github.com:x-dr/bing.git"
          # 注意替换为你的目标仓库地址
          gitee-repo: "ssh://git@git.tryxd.cn:222/ookk/bing_wallpaper.git"
